name: Update Mason Registry Lock

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Run registry update script
        run: ./generate_commits.sh

      - name: Push changes
        run: |
          if [ -n "$(git log origin/main..HEAD)" ]; then
            git push origin main
            echo "New commits pushed to main"
          else
            echo "No new commits to push"
          fi
